---
title: "Game of Thromes Character Ratings"
author: "Angela Zoss"
date: "2/1/2018"
output: github_document
---

## Setup your environment

```{r}

# Load required libraries

library(tidyverse)

```

## Load your data

```{r}

# data comes from https://int.nyt.com/newsgraphics/2017/2017-07-17-got-matrix/mean.json
# data based on ratings using tool at https://www.nytimes.com/interactive/2017/08/09/upshot/game-of-thrones-chart.html

got <- read_csv("../data/got_ratings.csv")

```

## Plot the data

```{r}

ggplot(got, aes(x=moral,y=physical)) +
  geom_point()

```

## Add labels

```{r}

ggplot(got, aes(x=moral,y=physical)) +
  geom_point() +
  geom_text(aes(label=label), nudge_y = -.03)

```

## Add colors

```{r}

ggplot(got, aes(x=moral,y=physical, color=gender)) +
  geom_point() +
  geom_text(aes(label=label), nudge_y = -.03)

```

## Switch Y axis

```{r}

ggplot(got, aes(x=moral,y=physical, color=gender)) +
  geom_point() +
  geom_text(aes(label=label), nudge_y = -.03) +
  scale_y_reverse()

```

## Add reference lines

```{r}

ggplot(got, aes(x=moral,y=physical, color=gender)) +
  geom_point() +
  scale_y_reverse() +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5) +
  geom_text(aes(label=label), nudge_y = -.03) 

```

## Change axis limits

```{r}

ggplot(got, aes(x=moral,y=physical, color=gender)) +
  geom_point() +
  scale_y_reverse(lim=c(1,0)) +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5) +
  geom_text(aes(label=label), nudge_y = -.03) +
  scale_x_continuous(limits=c(0,1))

```

## Change the theme

```{r}

ggplot(got, aes(x=moral,y=physical, color=gender)) +
  geom_point() +
  scale_y_reverse(lim=c(1,0)) +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5) +
  geom_text(aes(label=label), nudge_y = -.03) +
  scale_x_continuous(limits=c(0,1)) +
  theme_bw()

```

## Turn off legend for text layer

```{r}

ggplot(got, aes(x=moral,y=physical, color=gender)) +
  geom_point() +
  scale_y_reverse(lim=c(1,0)) +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5) +
  geom_text(aes(label=label), nudge_y = -.03, show.legend = FALSE) +
  scale_x_continuous(limits=c(0,1)) +
  theme_bw()

```

## Annotate the axes

```{r}

ggplot(got, aes(x=moral,y=physical, color=gender)) +
  geom_point() +
  scale_y_reverse(lim=c(1,0)) +
  geom_hline(yintercept=.5) +
  geom_vline(xintercept=.5) +
  geom_text(aes(label=label), nudge_y = -.03, show.legend = FALSE) +
  scale_x_continuous(limits=c(0,1)) +
  theme_bw() +
  annotate(geom = "text", x=.5, y=1, label="Ugly") +
  annotate(geom = "text", x=.5, y=0, label="Beautiful") +
  annotate(geom = "text", x=0, y=.48, label="Evil") +
  annotate(geom = "text", x=1, y=.52, label="Good") 

```

## Lighten the lines

```{r}

ggplot(got, aes(x=moral,y=physical, color=gender)) +
  geom_point() +
  scale_y_reverse(lim=c(1,0)) +
  geom_hline(yintercept=.5, color="gray50") +
  geom_vline(xintercept=.5, color="gray50") +
  geom_text(aes(label=label), nudge_y = -.03, show.legend = FALSE) +
  scale_x_continuous(limits=c(0,1)) +
  theme_bw() +
  annotate(geom = "text", x=.5, y=1, label="Ugly") +
  annotate(geom = "text", x=.5, y=0, label="Beautiful") +
  annotate(geom = "text", x=0, y=.48, label="Evil") +
  annotate(geom = "text", x=1, y=.52, label="Good") 

```
